export enum icons {
  LOGO = 'logo',
  MOON = 'moon',
  SUN = 'sun',
  LANGUAGE = 'language',
  RU = 'ru',
  EN = 'en',
  LOGOUT = 'logout',
  CHANGES = 'changes',
  SETTINGS = 'settings',
  EMAIL = 'email',
  NOTIFICATIONS = 'notifications',
  DOCS = 'docs',
  CALENDAR = 'calendar',
  TEAMS = 'teams',
  CHATS = 'chats',
  MAIN = 'main',
  PASSWORD = 'password',
  PASSWORD_OFF = 'passwordOff',
  CHECK = 'check',
  PHONE = 'phone',
  USERNAME = 'username',
  CROSS = 'cross',
  NOT_FOUND = '404',
  TELEGRAM = 'telegram',
  GITHUB = 'github',
  SEARCH = 'search'
}
